#!/usr/bin/env ruby
#^syntax detection
forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-stdlib'
mod 'puppetlabs-ntp'
mod 'fsalum-redis'
mod 'puppetlabs-mysql'
mod 'stankevich-python'
mod 'elasticsearch/elasticsearch'
